# Global settings for the updater.
# Global settings override individual settings when enabled.
Global:
    force_update_all: False # Force an update to every mod.
    loglevel: INFO          # Set to DEBUG for more info while executing
    executable: 'EoCApp.exe'
    autorun: True           # If true, the game will be launched after updating
    mod_folder: "%UserProfile%/Documents/Larian Studios/Divinity Original Sin 2 Definitive Edition/Mods"


## Mod list ##
# To add a mod, make a new entry with a similar structure as the following ones.
# Basic mods uploaded to a reasonable site should work out of the box
# Some mods have special handlers, Epip for instance only updates when the version in your mod folder is older than the most recent release.
# If filenames are specified for a mod, then that mod is not downloaded if the files are already there.
#   Use the force_update parameter or delete the files when you want to force an update.


# Epic Encounters
EpicEncounters:
    force_update: False
    url: https://drive.google.com/file/d/1loqIeAQsvNGlB2SD4b9QQC2fyb0B_qe9/view?usp=sharing
    filenames:
        - "Epic_Encounters_Core_63bb9b65-2964-4c10-be5b-55a63ec02fa0.pak"
        - "Epic_Encounters_d2d724e6-13c2-47c3-b356-19c3ff8bc622.pak"


# Epip Encounters
EpipEncounters:
    force_update: False
    url: https://www.pinewood.team/epip/patchnotes/
    metafile: '\DefEd\Data\Projects\EpipEncounters_7d32cb52-1cfd-4526-9b84-db4867bf9356\meta.lsx'


# Derpy's EE2 tweaks + Artifact tiers
Derpy:
    force_update: False
    url: https://drive.google.com/drive/folders/1BQnXOJ-iZm5QfXYwD9WJ0h3JNpPH2_gF
    filenames:
        - "Derpy's EE2 tweaks.pak"
        - "Derpy's Artifact Tiers.pak"


# Runepatch
RunePatch:
    force_update: False
    url: https://cdn.discordapp.com/attachments/608788140550914069/775764883500171304/runepatch.pak
    filenames:
        - "runepatch.pak"
