on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --onefile mod_updater.py
      - run: cp mod_updater_config.yaml dist/
      - uses: vimtor/action-zip@v1
        with:
          files: dist/mod_updater_config.yaml dist/mod_updater.exe
          dest: ./dist/mod_updater_${{github.ref_name}}.zip

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "TEST RELEASE DOS2 Mod Updater ${{github.ref_name}}"
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/mod_updater_${{github.ref_name}}.zip
          asset_name: mod_updater_${{github.ref_name}}.zip
          asset_content_type: application/zip
