name: Package Application with Pyinstaller

on:
  push:
    branches: [ release-test ]
  pull_request:
    branches: [ release-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@release-test
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows
